// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GraphView
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DeployScriptTemplate : DeployScriptTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
  
			var typeDictionary = new Dictionary<string, Tuple<string, string, int>>
			{
				{"int", new Tuple<string, string, int>("int", "SqlInt32", 4)},
				{"long", new Tuple<string, string, int>("bigint", "SqlInt64", 8)},
				{"double", new Tuple<string, string, int>("float", "SqlDouble", 8)},
				{"string", new Tuple<string, string, int>("nvarchar(4000)", "SqlString", 4)}
			};

            
            #line default
            #line hidden
            
            #line 16 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
 if (Type == 0) {
            
            #line default
            #line hidden
            this.Write(" \r\nCREATE ASSEMBLY ");
            
            #line 17 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly FROM ");
            
            #line 17 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path));
            
            #line default
            #line hidden
            this.Write("\r\nGO\r\n\r\n");
            
            #line 20 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var edge in EdgeList) {
	var edgeName = edge.Item1;
	var edgeColumnId = edge.Item2; //The edge has sink and source in the same table or not.
	var variables = edge.Item3;

            
            #line default
            #line hidden
            this.Write("CREATE FUNCTION ");
            
            #line 25 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 25 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(\r\n\t@array varbinary(max),\r\n\t@dele varbinary(max))\r\n\tRETURNS TABLE\r\n\t( \r\n" +
                    "\t\tSink bigint, EdgeId int");
            
            #line 30 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"

		for (var i = 0; i < variables.Count; ++i)
		{
			WriteLine(",");
			Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
		}
		WriteLine("");
	
            
            #line default
            #line hidden
            this.Write("\t)\r\nAS EXTERNAL NAME ");
            
            #line 39 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 39 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Decoder; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 42 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 42 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(\r\n@PathVarbinary varbinary(max), @nodeid bigint, @array v" +
                    "arbinary(max), @array2 varbinary(max)) RETURNs TABLE\r\n(\r\n\tEdgeId int, EdgeColumn" +
                    "Id bigint, Sink bigint");
            
            #line 45 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine("");

            
            #line default
            #line hidden
            this.Write(")\r\n  AS EXTERNAL NAME ");
            
            #line 54 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 54 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("ExclusiveEdgeGenerator;\r\nGO\r\n\r\ncreate function ");
            
            #line 57 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 57 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_bfs(@source bigint, \r\n\t\t@minlength bigint, @maxlength bigint,\r\n\t\t@edgeColumn var" +
                    "binary(max), @Del varbinary(max)\r\n");
            
            #line 60 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		WriteLine(", ");
		Write("		");
		Write("@" + it.Item1);
		Write(" " + typeDictionary[it.Item2].Item1);
}
            
            #line default
            #line hidden
            this.Write(@")
returns table
as 
return 
with  allPath(sink, varPath) as (
		select newpath.sink,  CAST(convert(binary(8), reverse(convert(binary(8), @source))) + 
		convert(binary(8), reverse(convert(binary(8), 3))) + convert(binary(4),reverse(convert(binary(4),newpath.EdgeId))) as varbinary(max))
		from ");
            
            #line 73 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 73 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(@edgeColumn, @Del) as newpath\r\n\t\tWhere (@maxlength != 0)\r\n");
            
            #line 75 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tunion all\r\n\r\n\t\tselect newpath.Sink, allpath.varPath + convert(binary(8), reve" +
                    "rse(convert(binary(8), allpath.sink))) + \r\n\t\tconvert(binary(8), reverse(convert(" +
                    "binary(8), ");
            
            #line 85 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeColumnId));
            
            #line default
            #line hidden
            this.Write("))) + convert(binary(4),reverse(convert(binary(4),newpath.EdgeId))) as Path\r\n\t\tfr" +
                    "om (allPath join ");
            
            #line 86 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(" on  allPath.sink = ");
            
            #line 86 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId)\r\n\t\tcross apply ");
            
            #line 87 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 87 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(allPath.varPath,");
            
            #line 87 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId,\r\n\t\t  ");
            
            #line 88 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 88 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 88 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 88 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("DeleteCol) as newPath\r\n\t\tWhere (@maxlength = -1 or DATALENGTH(allPath.varPath) <=" +
                    " (@maxlength - 1) * 20)\r\n");
            
            #line 90 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write(")\r\nselect @source as sink, CAST(0x as varbinary(max)) as varPath\r\nwhere @minlengt" +
                    "h = 0\r\nunion\r\nselect *\r\nfrom allPath\r\nwhere DATALENGTH(allPath.varPath) >= @minl" +
                    "ength * 20\r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 105 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 105 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder(\r\n\t@nodeType nvarchar(max), @id nvarchar(max),\r\n\t@edgeType nv" +
                    "archar(max)");
            
            #line 107 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("	@" + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}

            
            #line default
            #line hidden
            this.Write(")\r\nRETURNS varbinary(max)\r\nAS EXTERNAL NAME ");
            
            #line 114 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 114 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 117 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 117 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageDecoder(\r\n\t@array varbinary(max), @nodeType nvarchar(max),\r\n\t@id nvar" +
                    "char(max))\r\nRETURNS nvarchar(max)\r\nAS EXTERNAL NAME ");
            
            #line 121 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 121 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageDecoder; \r\nGO\r\n\r\ncreate function ");
            
            #line 124 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 124 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_bfs2(@source bigint, \r\n\t\t@minlength bigint, @maxlength bigint,\r\n\t\t@nodeType nvar" +
                    "char(max), @id nvarchar(max),\r\n\t\t@edgeColumn varbinary(max), @Del varbinary(max)" +
                    "\r\n");
            
            #line 128 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		WriteLine(", ");
		Write("		");
		Write("@" + it.Item1);
		Write(" " + typeDictionary[it.Item2].Item1);
}
            
            #line default
            #line hidden
            this.Write(@")
returns table
as 
return 
with  allPath(sink, varPath, PathMessage) as (
		select newpath.sink,  
		CAST(convert(binary(8), reverse(convert(binary(8), @source))) + 
			convert(binary(8), reverse(convert(binary(8), 3))) + 
			convert(binary(4),reverse(convert(binary(4),newpath.EdgeId))) as varbinary(max)) as varPath,
		dbo.");
            
            #line 143 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 143 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder(@nodeType, @id, \'");
            
            #line 143 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t");
            
            #line 144 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t,newpath.");
            
            #line 145 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 146 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(") as PathMessage\r\n\t\tfrom ");
            
            #line 147 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 147 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(@edgeColumn, @Del) as newpath\r\n\t\tWhere (@maxlength != 0)\r\n");
            
            #line 149 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tunion all\r\n\r\n\t\tselect newpath.Sink, allpath.varPath + convert(binary(8), reve" +
                    "rse(convert(binary(8), allpath.sink))) + \r\n\t\t\tconvert(binary(8), reverse(convert" +
                    "(binary(8), ");
            
            #line 159 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeColumnId));
            
            #line default
            #line hidden
            this.Write("))) + \r\n\t\t\tconvert(binary(4),reverse(convert(binary(4),newpath.EdgeId))) as varPa" +
                    "th,\r\n\t\t(allPath.PathMessage +\r\n\t\tdbo.");
            
            #line 162 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 162 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder(\'");
            
            #line 162 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write("\',\r\n\t\t\t");
            
            #line 163 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
if (String.IsNullOrEmpty(UserId)) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tnull\r\n\t\t\t");
            
            #line 165 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 166 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 166 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserId));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 167 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t, \'");
            
            #line 168 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t");
            
            #line 169 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t, newpath.");
            
            #line 170 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 171 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(")) as PathMessage\r\n\r\n\t\tfrom (allPath join ");
            
            #line 173 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(" on  allPath.sink = ");
            
            #line 173 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId)\r\n\t\tcross apply ");
            
            #line 174 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 174 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(allPath.varPath,");
            
            #line 174 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId,\r\n\t\t  ");
            
            #line 175 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 175 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 175 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 175 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("DeleteCol) as newPath\r\n\t\tWhere (@maxlength = -1 or DATALENGTH(allPath.varPath) <=" +
                    " (@maxlength - 1) * 20)\r\n");
            
            #line 177 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write(")\r\nselect @source as sink, CAST(0x as varbinary(max)) as varPath, CAST(0x as varb" +
                    "inary(max)) as PathMessage\r\nwhere @minlength = 0\r\nunion\r\nselect *\r\nfrom allPath\r" +
                    "\nwhere DATALENGTH(allPath.varPath) >= @minlength * 20\r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 192 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 192 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Recycle(@src varbinary(max), @toRecycle varbinary(max))\r\nRETURNS varbinary(max)\r" +
                    "\nEXTERNAL NAME ");
            
            #line 194 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 194 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Recycle;\r\nGO\r\n\r\nCREATE AGGREGATE ");
            
            #line 197 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 197 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Encoder\r\n(\r\n\t@Sink bigint");
            
            #line 199 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    @" + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine(""); 

            
            #line default
            #line hidden
            this.Write(")\r\nRETURNS varbinary(max)\r\nEXTERNAL NAME ");
            
            #line 209 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.");
            
            #line 209 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Encoder; \r\nGO\r\n\r\n");
            
            #line 212 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 213 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 216 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
 if (Type == 1) {
            
            #line default
            #line hidden
            
            #line 217 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
foreach (var edge in EdgeList) {
	var edgeName = edge.Item1;
	var variables = edge.Item3;

            
            #line default
            #line hidden
            this.Write("CREATE ASSEMBLY ");
            
            #line 221 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 221 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly FROM ");
            
            #line 221 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path));
            
            #line default
            #line hidden
            this.Write("\r\nGO\r\nCREATE FUNCTION ");
            
            #line 223 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 223 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(\r\n");
            
            #line 224 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
for (int i = 0; i < InputCount; i++) {
            
            #line default
            #line hidden
            this.Write("@array");
            
            #line 225 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max), @dele");
            
            #line 225 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max)");
            
            #line 225 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
 if (i != InputCount - 1) WriteLine(","); 
            
            #line default
            #line hidden
            
            #line 226 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(") RETURNS TABLE\r\n(\r\n\tSink bigint, EdgeColumnId bigint, EdgeId int, _EdgeType nvar" +
                    "char(max)");
            
            #line 228 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine("");

            
            #line default
            #line hidden
            this.Write(") \r\n  AS EXTERNAL NAME ");
            
            #line 237 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 237 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 237 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Decoder; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 240 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 240 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(\r\n@PathVarbinary varbinary(max), @nodeid bigint, \r\n");
            
            #line 242 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
for (int i = 0; i < InputCount; i++) {
            
            #line default
            #line hidden
            this.Write("@array");
            
            #line 243 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max), @dele");
            
            #line 243 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max)");
            
            #line 243 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
 if (i != InputCount - 1) WriteLine(","); 
            
            #line default
            #line hidden
            
            #line 244 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(") RETURNs TABLE\r\n(\r\n\tEdgeId int, EdgeColumnId bigint, Sink bigint, _EdgeType nvar" +
                    "char(max)");
            
            #line 246 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine("");

            
            #line default
            #line hidden
            this.Write(")\r\n  AS EXTERNAL NAME ");
            
            #line 255 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 255 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 255 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("ExclusiveEdgeGenerator; \r\nGO\r\n");
            
            #line 257 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 258 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 261 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
 if (Type == 2) {
            
            #line default
            #line hidden
            this.Write("CREATE ASSEMBLY ");
            
            #line 262 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly FROM ");
            
            #line 262 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path));
            
            #line default
            #line hidden
            this.Write("\r\nGO\r\n\r\nCREATE AGGREGATE ");
            
            #line 265 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("GlobalNodeIdEncoder\r\n(\r\n\t@SrcId bigint\r\n)\r\nRETURNS varbinary(max)\r\nEXTERNAL NAME " +
                    "");
            
            #line 270 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.GlobalNodeIdEncoder; \r\nGO\r\nCREATE AGGREGATE ");
            
            #line 272 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("EdgeIdEncoder\r\n(\r\n\t@EdgeId int\r\n)\r\nRETURNS varbinary(max)\r\nEXTERNAL NAME ");
            
            #line 277 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.EdgeIdEncoder; \r\nGO\r\n\r\nCREATE FUNCTION SingletonTable() RETURNS TABLE\r\n(" +
                    "\r\n\tmemoBit bit\r\n)\r\nas EXTERNAL NAME ");
            
            #line 284 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.UserDefinedFunctions.SingletonTable\r\nGO\r\n\r\nCREATE FUNCTION DownSizeFunct" +
                    "ion\r\n(@id int)\r\nRETURNS INT\r\nAS\r\n EXTERNAL NAME ");
            
            #line 291 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.UserDefinedFunctions.DownSizeFunction\r\nGO\r\n\r\nCREATE FUNCTION UpSizeFunct" +
                    "ion(@topvalue int) RETURNS TABLE\r\nAS\r\nRETURN\r\n\tSELECT TOP(@topvalue) * FROM Sing" +
                    "letonTable()\r\nGO\r\n");
            
            #line 299 "D:\Source\graphview\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class DeployScriptTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
