// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GraphView
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Source\GraphView\DeployScriptTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DeployScriptTemplate : DeployScriptTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\Source\GraphView\DeployScriptTemplate.tt"
  
			var typeDictionary = new Dictionary<string, Tuple<string, string, int>>
			{
				{"int", new Tuple<string, string, int>("int", "SqlInt32", 4)},
				{"long", new Tuple<string, string, int>("bigint", "SqlInt64", 8)},
				{"double", new Tuple<string, string, int>("float", "SqlDouble", 8)},
				{"string", new Tuple<string, string, int>("nvarchar(4000)", "SqlString", 4)},
				{"bool", new Tuple<string, string, int>("bit", "SqlBoolean", 1)}
			};

            
            #line default
            #line hidden
            this.Write("--NodeTable UDF\r\n");
            
            #line 18 "D:\Source\GraphView\DeployScriptTemplate.tt"
 if (Type == 0) {
            
            #line default
            #line hidden
            this.Write(" \r\nCREATE ASSEMBLY ");
            
            #line 19 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly FROM ");
            
            #line 19 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path));
            
            #line default
            #line hidden
            this.Write("\r\nGO\r\n\r\n");
            
            #line 22 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var edge in EdgeList) {
	var edgeName = edge.Item1;
	var edgeColumnId = edge.Item2; //The edge has sink and source in the same table or not.
	var variables = edge.Item3;

            
            #line default
            #line hidden
            this.Write("CREATE FUNCTION ");
            
            #line 27 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 27 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(\r\n\t@array varbinary(max),\r\n\t@dele varbinary(max),\r\n\t@dumb bigint = 0)\r\n\t" +
                    "RETURNS TABLE\r\n\t( \r\n\t\tSink bigint, EdgeId int");
            
            #line 33 "D:\Source\GraphView\DeployScriptTemplate.tt"

		for (var i = 0; i < variables.Count; ++i)
		{
			WriteLine(",");
			Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
		}
		WriteLine("");
	
            
            #line default
            #line hidden
            this.Write("\t)\r\nAS EXTERNAL NAME ");
            
            #line 42 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 42 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Decoder; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 45 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 45 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(\r\n@PathVarbinary varbinary(max), @nodeid bigint, @array v" +
                    "arbinary(max), @array2 varbinary(max)) RETURNs TABLE\r\n(\r\n\tEdgeId int, EdgeColumn" +
                    "Id int, Sink bigint");
            
            #line 48 "D:\Source\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine("");

            
            #line default
            #line hidden
            this.Write(")\r\n  AS EXTERNAL NAME ");
            
            #line 57 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 57 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("ExclusiveEdgeGenerator;\r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 60 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 60 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveNodeGenerator(\r\n@PathVarbinary varbinary(max), @array varbinary(max), @" +
                    "array2 varbinary(max)) RETURNs TABLE\r\n(\r\n   Sink bigint\r\n)\r\n  AS EXTERNAL NAME ");
            
            #line 65 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 65 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("ExclusiveNodeGenerator;\r\nGO\r\n\r\ncreate function ");
            
            #line 68 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 68 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_bfsPath(@source bigint, \r\n\t\t@minlength bigint, @maxlength bigint,\r\n\t\t@edgeColumn" +
                    " varbinary(max), @Del varbinary(max)\r\n");
            
            #line 71 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		WriteLine(", ");
		Write("		");
		Write("@" + it.Item1);
		Write(" " + typeDictionary[it.Item2].Item1);
}
            
            #line default
            #line hidden
            this.Write(")\r\nreturns table\r\nas \r\nreturn \r\nwith  allPath(sink, varPath) as (\r\n\t\tselect newpa" +
                    "th.sink,  \r\n\t\tdbo.ConvertNumberIntoBinaryForPath(@source, ");
            
            #line 83 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeColumnId));
            
            #line default
            #line hidden
            this.Write(", newpath.EdgeId)\r\n\t\tfrom ");
            
            #line 84 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 84 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(@edgeColumn, @Del, 0) as newpath\r\n\t\tWhere (@maxlength != 0)\r\n");
            
            #line 86 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tunion all\r\n\r\n\t\tselect newpath.Sink, allpath.varPath + \r\n\t\t\r\n\t\tdbo.ConvertNumb" +
                    "erIntoBinaryForPath(allpath.sink, ");
            
            #line 97 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeColumnId));
            
            #line default
            #line hidden
            this.Write(", newpath.EdgeId) as Path\r\n\t\tfrom (allPath join ");
            
            #line 98 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(" on  allPath.sink = ");
            
            #line 98 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId)\r\n\t\tcross apply ");
            
            #line 99 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 99 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(allPath.varPath,");
            
            #line 99 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId,\r\n\t\t  ");
            
            #line 100 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 100 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 100 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 100 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("DeleteCol) as newPath\r\n\t\tWhere (@maxlength = -1 or DATALENGTH(allPath.varPath) <=" +
                    " (@maxlength - 1) * 16)\r\n");
            
            #line 102 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write(")\r\nselect @source as sink, CAST(0x as varbinary(max)) as varPath\r\nwhere @minlengt" +
                    "h = 0\r\nunion all\r\nselect *\r\nfrom allPath\r\nwhere DATALENGTH(allPath.varPath) >= @" +
                    "minlength * 16\r\nGO\r\n\r\ncreate function ");
            
            #line 117 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 117 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(@"_bfsPath_DifferNodes(@source bigint, 
		@minlength bigint, @maxlength bigint,
		@edgeColumn varbinary(max), @Del varbinary(max)
)
returns table
as 
return 
with  allPath(sink, varPath) as (
		select newpath.sink,  
		dbo.ConvertInt64IntoVarbinary(@source) + dbo.ConvertInt64IntoVarbinary(newpath.sink)
		from ");
            
            #line 127 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 127 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(@"_ExclusiveNodeGenerator(dbo.ConvertInt64IntoVarbinary(@source), @edgeColumn, @Del) as newpath
		Where (@maxlength != 0)

		union all

		select newpath.Sink, allpath.varPath + 
		dbo.ConvertInt64IntoVarbinary(newpath.sink) as Path

		from (allPath join ");
            
            #line 135 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(" on  allPath.sink = ");
            
            #line 135 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId)\r\n\t\tcross apply ");
            
            #line 136 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 136 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveNodeGenerator(allPath.varPath,\r\n\t\t  ");
            
            #line 137 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 137 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 137 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 137 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(@"DeleteCol) as newPath

		Where (@maxlength = -1 or DATALENGTH(allPath.varPath) <= (@maxlength) * 8)
)
select @source as sink, dbo.ConvertInt64IntoVarbinary(@source) as varPath
where @minlength = 0
union all
select *
from allPath
where DATALENGTH(allPath.varPath) >= (@minlength + 1) * 8 
GO

CREATE FUNCTION ");
            
            #line 149 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 149 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder(\r\n\t@nodeType nvarchar(max), @id nvarchar(max),\r\n\t@edgeType nv" +
                    "archar(max)");
            
            #line 151 "D:\Source\GraphView\DeployScriptTemplate.tt"
for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("	@" + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}

            
            #line default
            #line hidden
            this.Write(")\r\nRETURNS varbinary(max)\r\nAS EXTERNAL NAME ");
            
            #line 158 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 158 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 161 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 161 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageDecoder(\r\n\t@array varbinary(max), @nodeType nvarchar(max),\r\n\t@id nvar" +
                    "char(max))\r\nRETURNS nvarchar(max)\r\nAS EXTERNAL NAME ");
            
            #line 165 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 165 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageDecoder; \r\nGO\r\n\r\ncreate function ");
            
            #line 168 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 168 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_bfsPathWithMessage(@source bigint, \r\n\t\t@minlength bigint, @maxlength bigint,\r\n\t\t" +
                    "@nodeType nvarchar(max), @id nvarchar(max),\r\n\t\t@edgeColumn varbinary(max), @Del " +
                    "varbinary(max)\r\n");
            
            #line 172 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		WriteLine(", ");
		Write("		");
		Write("@" + it.Item1);
		Write(" " + typeDictionary[it.Item2].Item1);
}
            
            #line default
            #line hidden
            this.Write(")\r\nreturns table\r\nas \r\nreturn \r\nwith  allPath(sink, varPath, PathMessage) as (\r\n\t" +
                    "\tselect newpath.sink,  \r\n\t\tdbo.ConvertNumberIntoBinaryForPath(@source, ");
            
            #line 184 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeColumnId));
            
            #line default
            #line hidden
            this.Write(", newpath.EdgeId) as varPath,\r\n\t\tdbo.");
            
            #line 185 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 185 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder(@nodeType, @id, \'");
            
            #line 185 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t");
            
            #line 186 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t,newpath.");
            
            #line 187 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 188 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(") as PathMessage\r\n\t\tfrom ");
            
            #line 189 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 189 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(@edgeColumn, @Del, 0) as newpath\r\n\t\tWhere (@maxlength != 0)\r\n");
            
            #line 191 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tunion all\r\n\r\n\t\tselect newpath.Sink, allpath.varPath + \r\n\t\tdbo.ConvertNumberIn" +
                    "toBinaryForPath(allpath.sink, ");
            
            #line 201 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeColumnId));
            
            #line default
            #line hidden
            this.Write(", newpath.EdgeId) as varPath,\r\n\t\t(allPath.PathMessage +\r\n\t\tdbo.");
            
            #line 203 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 203 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder(\'");
            
            #line 203 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write("\',\r\n\t\t\t");
            
            #line 204 "D:\Source\GraphView\DeployScriptTemplate.tt"
if (String.IsNullOrEmpty(UserId)) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tnull\r\n\t\t\t");
            
            #line 206 "D:\Source\GraphView\DeployScriptTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 207 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 207 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserId));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 208 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t, \'");
            
            #line 209 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t");
            
            #line 210 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t, newpath.");
            
            #line 211 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 212 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(")) as PathMessage\r\n\r\n\t\tfrom (allPath join ");
            
            #line 214 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(" on  allPath.sink = ");
            
            #line 214 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId)\r\n\t\tcross apply ");
            
            #line 215 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 215 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(allPath.varPath,");
            
            #line 215 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".GlobalNodeId,\r\n\t\t  ");
            
            #line 216 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 216 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 216 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NodeTable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 216 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("DeleteCol) as newPath\r\n\t\tWhere (@maxlength = -1 or DATALENGTH(allPath.varPath) <=" +
                    " (@maxlength - 1) * 16)\r\n");
            
            #line 218 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var it in variables) {
		Write("		");
		Write("and (");
		Write("@" + it.Item1 + " is null or ");
		WriteLine("@" + it.Item1 + " = newPath." + it.Item1 + ")");
}
            
            #line default
            #line hidden
            this.Write(")\r\nselect @source as sink, CAST(0x as varbinary(max)) as varPath, CAST(0x as varb" +
                    "inary(max)) as PathMessage\r\nwhere @minlength = 0\r\nunion all\r\nselect *\r\nfrom allP" +
                    "ath\r\nwhere DATALENGTH(allPath.varPath) >= @minlength * 16\r\nGO\r\n\r\nCREATE FUNCTION" +
                    " ");
            
            #line 233 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 233 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Recycle(@src varbinary(max), @toRecycle varbinary(max))\r\nRETURNS varbinary(max)\r" +
                    "\nEXTERNAL NAME ");
            
            #line 235 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 235 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Recycle;\r\nGO\r\n\r\nCREATE AGGREGATE ");
            
            #line 238 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 238 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Encoder\r\n(\r\n\t@Sink bigint");
            
            #line 240 "D:\Source\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    @" + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine(""); 

            
            #line default
            #line hidden
            this.Write(")\r\nRETURNS varbinary(max)\r\nEXTERNAL NAME ");
            
            #line 250 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_Assembly.");
            
            #line 250 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Encoder; \r\nGO\r\n\r\n");
            
            #line 253 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 254 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n--Edge view UDF\r\n");
            
            #line 257 "D:\Source\GraphView\DeployScriptTemplate.tt"
 if (Type == 1) {
            
            #line default
            #line hidden
            
            #line 258 "D:\Source\GraphView\DeployScriptTemplate.tt"
foreach (var edge in EdgeList) {
	var edgeName = edge.Item1;
	var variables = edge.Item3;

            
            #line default
            #line hidden
            this.Write("CREATE ASSEMBLY ");
            
            #line 262 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 262 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly FROM ");
            
            #line 262 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path));
            
            #line default
            #line hidden
            this.Write("\r\nGO\r\nCREATE FUNCTION ");
            
            #line 264 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 264 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Decoder(\r\n");
            
            #line 265 "D:\Source\GraphView\DeployScriptTemplate.tt"
for (int i = 0; i < InputCount; i++) {
            
            #line default
            #line hidden
            this.Write("@array");
            
            #line 266 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max), @dele");
            
            #line 266 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max)");
            
            #line 266 "D:\Source\GraphView\DeployScriptTemplate.tt"
 WriteLine(","); 
            
            #line default
            #line hidden
            
            #line 267 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("@dumb bigint = 0) RETURNS TABLE\r\n(\r\n\tSink bigint, EdgeColumnId int, EdgeId int, _" +
                    "EdgeType nvarchar(max)");
            
            #line 269 "D:\Source\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine("");

            
            #line default
            #line hidden
            this.Write(") \r\n  AS EXTERNAL NAME ");
            
            #line 278 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 278 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 278 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("Decoder; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 281 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 281 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_ExclusiveEdgeGenerator(\r\n@PathVarbinary varbinary(max), @nodeid bigint, \r\n");
            
            #line 283 "D:\Source\GraphView\DeployScriptTemplate.tt"
for (int i = 0; i < InputCount; i++) {
            
            #line default
            #line hidden
            this.Write("@array");
            
            #line 284 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max), @dele");
            
            #line 284 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" varbinary(max)");
            
            #line 284 "D:\Source\GraphView\DeployScriptTemplate.tt"
 if (i != InputCount - 1) WriteLine(","); 
            
            #line default
            #line hidden
            
            #line 285 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(") RETURNs TABLE\r\n(\r\n\tEdgeId int, EdgeColumnId int, Sink bigint, _EdgeType nvarcha" +
                    "r(max)");
            
            #line 287 "D:\Source\GraphView\DeployScriptTemplate.tt"

	for (var i = 0; i < variables.Count; ++i)
	{
		WriteLine(",");
		Write("    " + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
	}
	WriteLine("");

            
            #line default
            #line hidden
            this.Write(")\r\n  AS EXTERNAL NAME ");
            
            #line 296 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 296 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 296 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("ExclusiveEdgeGenerator; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 299 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 299 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder(\r\n    @nodeType nvarchar(max), @id nvarchar(max),\r\n    @edgeT" +
                    "ype nvarchar(max)");
            
            #line 301 "D:\Source\GraphView\DeployScriptTemplate.tt"
for (var i = 0; i < variables.Count; ++i)
    {
        WriteLine(",");
        Write(" @" + variables[i].Item1 + " " + typeDictionary[variables[i].Item2].Item1);
    }

            
            #line default
            #line hidden
            this.Write(")\r\nRETURNS varbinary(max)\r\nAS EXTERNAL NAME ");
            
            #line 308 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 308 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 308 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageEncoder; \r\nGO\r\n\r\nCREATE FUNCTION ");
            
            #line 311 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 311 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageDecoder(\r\n    @array varbinary(max), @nodeType nvarchar(max),\r\n    @i" +
                    "d nvarchar(max))\r\nRETURNS nvarchar(max)\r\nAS EXTERNAL NAME ");
            
            #line 315 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 315 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_Assembly.UserDefinedFunctions.");
            
            #line 315 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(edgeName));
            
            #line default
            #line hidden
            this.Write("_PathMessageDecoder; \r\nGO\r\n");
            
            #line 317 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 318 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n--Meta UDF\r\n");
            
            #line 321 "D:\Source\GraphView\DeployScriptTemplate.tt"
 if (Type == 2) {
            
            #line default
            #line hidden
            this.Write("CREATE ASSEMBLY ");
            
            #line 322 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly FROM ");
            
            #line 322 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path));
            
            #line default
            #line hidden
            this.Write("\r\nGO\r\n\r\nCREATE AGGREGATE ");
            
            #line 325 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("GlobalNodeIdEncoder\r\n(\r\n\t@SrcId bigint\r\n)\r\nRETURNS varbinary(max)\r\nEXTERNAL NAME " +
                    "");
            
            #line 330 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.GlobalNodeIdEncoder; \r\nGO\r\nCREATE AGGREGATE ");
            
            #line 332 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("EdgeIdEncoder\r\n(\r\n\t@EdgeId int\r\n)\r\nRETURNS varbinary(max)\r\nEXTERNAL NAME ");
            
            #line 337 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.EdgeIdEncoder; \r\nGO\r\n\r\nCREATE FUNCTION SingletonTable() RETURNS TABLE\r\n(" +
                    "\r\n\tmemoBit bit\r\n)\r\nas EXTERNAL NAME ");
            
            #line 344 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.UserDefinedFunctions.SingletonTable\r\nGO\r\n\r\nCREATE FUNCTION SingletonTabl" +
                    "e2(@dumb bigint) RETURNS TABLE\r\n(\r\n\tmemoBit bit\r\n)\r\nas EXTERNAL NAME ");
            
            #line 351 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.UserDefinedFunctions.SingletonTable2\r\nGO\r\n\r\nCREATE FUNCTION DownSizeFunc" +
                    "tion\r\n(@id int)\r\nRETURNS INT\r\nAS\r\n EXTERNAL NAME ");
            
            #line 358 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write(@"Assembly.UserDefinedFunctions.DownSizeFunction
GO

CREATE FUNCTION UpSizeFunction(@topvalue int) RETURNS TABLE
AS
RETURN
	SELECT TOP(@topvalue) * FROM SingletonTable()
GO

CREATE FUNCTION UpSizeFunction2(@topvalue int, @dumb bigint) RETURNS TABLE
AS
RETURN
	SELECT TOP(@topvalue) * FROM SingletonTable2(@dumb)
GO

CREATE FUNCTION ConvertNumberIntoBinaryForPath(@a bigint, @b int, @c int)
RETURNS varbinary(max)
EXTERNAL NAME ");
            
            #line 375 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.UserDefinedFunctions.ConvertNumberIntoBinaryForPath;\r\nGO\r\n\r\nCREATE FUNCT" +
                    "ION ConvertInt64IntoVarbinary(@a bigint)\r\nRETURNS varbinary(max)\r\nEXTERNAL NAME " +
                    "");
            
            #line 380 "D:\Source\GraphView\DeployScriptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssemblyName));
            
            #line default
            #line hidden
            this.Write("Assembly.UserDefinedFunctions.ConvertInt64IntoVarbinary;\r\nGO\r\n");
            
            #line 382 "D:\Source\GraphView\DeployScriptTemplate.tt"
}
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class DeployScriptTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
