// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GraphView
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Source\graphview\GraphView\MetaGraphViewCodeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class MetaGraphViewCodeTemplate : MetaGraphViewCodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(" \r\nusing System;\r\nusing System.IO;\r\nusing System.Collections;\r\nusing System.Colle" +
                    "ctions.Generic;\r\nusing System.Data.SqlTypes;\r\nusing System.Text;\r\nusing Microsof" +
                    "t.SqlServer.Server;\r\n\r\npublic partial class UserDefinedFunctions\r\n{\r\n  private c" +
                    "lass SingletonTableDecoderResult\r\n  {\r\n    public bool bit { get; set; }\r\n  }\r\n\r" +
                    "\n  public static void SingletonTable_FillRow(\r\n      object tableTypeObject,\r\n  " +
                    "    out SqlBoolean bit)\r\n  {\r\n    var decoderResult = (SingletonTableDecoderResu" +
                    "lt)tableTypeObject;\r\n    bit = decoderResult.bit;\r\n  }\r\n\r\n  [SqlFunction(\r\n     " +
                    " DataAccess = DataAccessKind.None,\r\n      TableDefinition = \"ghostbit bit\",\r\n   " +
                    "   FillRowMethodName = \"SingletonTable_FillRow\",\r\n      IsDeterministic = true,\r" +
                    "\n      IsPrecise = false\r\n      )]\r\n    public static IEnumerable SingletonTable" +
                    "()\r\n    {\r\n\r\n      yield return new SingletonTableDecoderResult\r\n      {\r\n      " +
                    "  bit = true,\r\n      };\r\n    }\r\n\r\n\t[Microsoft.SqlServer.Server.SqlFunction]\r\n   " +
                    " public static SqlInt32 DownSizeFunction(SqlInt32 Checksum)\r\n    {\r\n      return" +
                    " new SqlInt32(1);\r\n    }\r\n\r\n\t[Microsoft.SqlServer.Server.SqlFunction]\r\n    publi" +
                    "c static byte[] ConvertNumberIntoBinaryForPath(SqlInt64 sink, \r\n\tSqlInt64 edgeCo" +
                    "lumnId, SqlInt32 edgeId)\r\n    {\r\n\t\tbyte[] _buffer = new byte[20];\r\n\t\tvar\t_stream" +
                    " = new MemoryStream(_buffer);\r\n\t\tvar _writer = new BinaryWriter(_stream);\r\n\t\t_wr" +
                    "iter.Write(sink.Value);\r\n\t\t_writer.Write(edgeColumnId.Value);\r\n\t\t_writer.Write(e" +
                    "dgeId.Value);\r\n\t\treturn _buffer;\r\n    }\r\n}\r\n\r\n[Serializable]\r\n[Microsoft.SqlServ" +
                    "er.Server.SqlUserDefinedAggregate(Format.UserDefined,\r\n    IsInvariantToNulls = " +
                    "true,\r\n    IsInvariantToOrder = true,\r\n    IsInvariantToDuplicates = false,\r\n   " +
                    " MaxByteSize = -1)]\r\npublic struct EdgeIdEncoder : IBinarySerialize\r\n{\r\n  privat" +
                    "e MemoryStream _stream;\r\n  private BinaryWriter _writer;\r\n\r\n  public void Init()" +
                    "\r\n  {\r\n    _stream = new MemoryStream();\r\n    _writer = new BinaryWriter(_stream" +
                    ");\r\n  }\r\n  public void Accumulate(SqlInt32 edgeid)\r\n  {\r\n    if (edgeid.IsNull)\r" +
                    "\n      return;\r\n    _writer.Write(edgeid.Value);\r\n\r\n  }\r\n\r\n  public void Merge (" +
                    "EdgeIdEncoder group)\r\n  {\r\n    _writer.Write(group._stream.GetBuffer(), 0, (int)" +
                    " group._stream.Length);\r\n  }\r\n\r\n  public SqlBytes Terminate()\r\n  {\r\n    return n" +
                    "ew SqlBytes(_stream);\r\n  }\r\n\r\n  public void Read(BinaryReader r)\r\n  {\r\n    if (_" +
                    "stream != null)\r\n      _stream.Dispose();\r\n    if (_writer != null)\r\n      _writ" +
                    "er.Dispose();\r\n    _stream = new MemoryStream();\r\n    _writer = new BinaryWriter" +
                    "(_stream);\r\n    _writer.Write(r.ReadBytes((int)r.BaseStream.Length));\r\n  }\r\n\r\n  " +
                    "public void Write(BinaryWriter w)\r\n  {\r\n    w.Write(_stream.GetBuffer(), 0, (int" +
                    ") _stream.Length);\r\n  }\r\n\r\n\r\n}\r\n\r\n[Serializable]\r\n[Microsoft.SqlServer.Server.Sq" +
                    "lUserDefinedAggregate(Format.UserDefined,\r\n    IsInvariantToNulls = true,\r\n    I" +
                    "sInvariantToOrder = true,\r\n    IsInvariantToDuplicates = false,\r\n    MaxByteSize" +
                    " = -1)]\r\npublic struct GlobalNodeIdEncoder : IBinarySerialize\r\n{\r\n  private Memo" +
                    "ryStream _stream;\r\n  private BinaryWriter _writer;\r\n\r\n  public void Init()\r\n  {\r" +
                    "\n    _stream = new MemoryStream();\r\n    _writer = new BinaryWriter(_stream);\r\n  " +
                    "}\r\n\r\n  public void Accumulate(\r\n      SqlInt64 sink)\r\n  {\r\n    if (sink.IsNull)\r" +
                    "\n      return;\r\n    _writer.Write(sink.Value);\r\n  }\r\n\r\n\r\n  public void Merge (Gl" +
                    "obalNodeIdEncoder group)\r\n  {\r\n    _writer.Write(group._stream.GetBuffer(), 0, (" +
                    "int) group._stream.Length);\r\n  }\r\n\r\n  public SqlBytes Terminate()\r\n  {\r\n    retu" +
                    "rn new SqlBytes(_stream);\r\n  }\r\n\r\n  public void Read(BinaryReader r)\r\n  {\r\n    i" +
                    "f (_stream != null)\r\n      _stream.Dispose();\r\n    if (_writer != null)\r\n      _" +
                    "writer.Dispose();\r\n    _stream = new MemoryStream();\r\n    _writer = new BinaryWr" +
                    "iter(_stream);\r\n    _writer.Write(r.ReadBytes((int)r.BaseStream.Length));\r\n  }\r\n" +
                    "\r\n  public void Write(BinaryWriter w)\r\n  {\r\n    w.Write(_stream.GetBuffer(), 0, " +
                    "(int)_stream.Length);\r\n  }\r\n\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class MetaGraphViewCodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
