//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRawRecordService")]
public interface IRawRecordService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRawRecordService/SendRawRecord", ReplyAction="http://tempuri.org/IRawRecordService/SendRawRecordResponse")]
    void SendRawRecord(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRawRecordService/SendRawRecord", ReplyAction="http://tempuri.org/IRawRecordService/SendRawRecordResponse")]
    System.Threading.Tasks.Task SendRawRecordAsync(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRawRecordService/SendSignal", ReplyAction="http://tempuri.org/IRawRecordService/SendSignalResponse")]
    void SendSignal(int index);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRawRecordService/SendSignal", ReplyAction="http://tempuri.org/IRawRecordService/SendSignalResponse")]
    System.Threading.Tasks.Task SendSignalAsync(int index);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRawRecordServiceChannel : IRawRecordService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RawRecordServiceClient : System.ServiceModel.ClientBase<IRawRecordService>, IRawRecordService
{
    
    public RawRecordServiceClient()
    {
    }
    
    public RawRecordServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RawRecordServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RawRecordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RawRecordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SendRawRecord(string message)
    {
        base.Channel.SendRawRecord(message);
    }
    
    public System.Threading.Tasks.Task SendRawRecordAsync(string message)
    {
        return base.Channel.SendRawRecordAsync(message);
    }
    
    public void SendSignal(int index)
    {
        base.Channel.SendSignal(index);
    }
    
    public System.Threading.Tasks.Task SendSignalAsync(int index)
    {
        return base.Channel.SendSignalAsync(index);
    }
}
